Create mygovau-7d9649.yml
phish-report/IOK pull request #194
Opened 2023-04-04 20:46 UTC by cybercrymen

IOK rule for MyGov Australia phishing kit detection.

2023-04-04 22:01 UTC, IlluminatiFish requested changes
Please consider the requested changes

2023-04-05 01:51 UTC, IlluminatiFish commented on indicators/mygovau-7d9649.yml
> +    chromeHTMLFragments:
Also, I think the killbot API key (`Gwhrue6nv7INVxMChew6XgpGD3_aLJ3imwX5OnvbETNpA`) left by the threat actor should be a detection string as it has a high entropy value 

I also think that the id (`00NF000000DAKs6`) of the input field where the IP of the visitor is stored, would be a good candidate for a detection string

The CSRF token may also be of use `31f75120-71a5-4089-8840-1c95d0e3443d` as it also has high entropy

2023-04-05 03:28 UTC, cybercrymen reviewed
Made those changes to the file

2023-04-05 20:13 UTC, IlluminatiFish approved these changes
LGTM

2023-04-05 20:35 UTC, merged