add Roblox phishing
phish-report/IOK pull request #252
Opened 2024-05-07 17:48 UTC by Czdam0

Detects Roblox phishing sites using a roblox body id and cdn.
Usually at /controlPage/create you can create a "Beaming link".
Often spread trough discord.

references
  - https://www.youtube.com/watch?v=lUL2vgyhsw4
  - https://urlscan.io/result/c716b820-174e-4211-9c09-4663b4a7e47d/
  - https://urlscan.io/result/c716b820-174e-4211-9c09-4663b4a7e47d/
  - https://urlscan.io/result/e76d7a2f-3e6d-455e-8da8-1a94ea6c222f/
  - https://urlscan.io/result/f9ccb8a3-624b-4cb1-b237-36dd81cef6e3/
  - https://urlscan.io/result/1a62439f-de11-4ee6-a0ed-9c482c0c1906/

2024-05-09 01:23 UTC, IlluminatiFish commented on indicators/roblox-phishing.yml
> +level: likely_malicious
The use of `level` in the public ruleset can be omitted.

2024-05-09 01:24 UTC, IlluminatiFish commented on indicators/roblox-phishing.yml
> +title: Roblox phishing
Please follow the rule naming convention specified in `CONTRIBUTING.md`. Typically the rule title and file name are the same.

2024-05-09 01:25 UTC, IlluminatiFish commented on indicators/roblox-phishing.yml
> +  - https://urlscan.io/result/c716b820-174e-4211-9c09-4663b4a7e47d/
It seems you have a duplicate reference here.

2024-05-09 01:26 UTC, IlluminatiFish requested changes
Please make the requested changes.

2024-05-09 05:36 UTC, Czdam0 commented
Thank you for bringing these issues to my attention. I have fixed these issues.

2024-05-09 17:19 UTC, Czdam0 reviewed
.

2024-05-20 08:03 UTC, IlluminatiFish approved these changes

2024-05-20 08:26 UTC, merged